window.CHEAT_DATA = [
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Getting Started",
    name: "Open cheat console",
    code: "L1 + L2 + R1 + R2",
    effect: "Opens the cheat console on PlayStation.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "official",
    notes: "Enter this while in a live save."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Getting Started",
    name: "Activate cheats",
    code: "testingcheats on",
    effect: "Enables most cheats for the current save.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "official",
    notes: "Using testingcheats disables trophies/achievements for that save."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Get 1,000 Simoleons",
    code: "kaching",
    effect: "Adds 1,000 Simoleons.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Basic money cheat."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Get 1,000 Simoleons (alias)",
    code: "rosebud",
    effect: "Adds 1,000 Simoleons.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Same result as kaching."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Get 50,000 Simoleons",
    code: "motherlode",
    effect: "Adds 50,000 Simoleons.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Classic Sims money cheat."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Set exact household funds",
    code: "money [amount]",
    effect: "Sets household funds to the exact amount you enter.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Example: money 250000"
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Free houses on",
    code: "FreeRealEstate on",
    effect: "Makes residential lots free while moving households.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Use from the world or moving screen."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Free houses off",
    code: "FreeRealEstate off",
    effect: "Turns off free house pricing.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Restores normal lot prices."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Autopay bills on",
    code: "household.autopay_bills true",
    effect: "Turns on automatic bill payment.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Convenience cheat."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Money",
    name: "Autopay bills off",
    code: "household.autopay_bills false",
    effect: "Turns off automatic bill payment.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Bills return to normal manual payment."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Astronaut",
    code: "careers.promote astronaut",
    effect: "Promotes the active Sim in the Astronaut career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Athlete",
    code: "careers.promote athletic",
    effect: "Promotes the active Sim in the Athlete career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Business",
    code: "careers.promote business",
    effect: "Promotes the active Sim in the Business career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Criminal",
    code: "careers.promote criminal",
    effect: "Promotes the active Sim in the Criminal career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Culinary",
    code: "careers.promote culinary",
    effect: "Promotes the active Sim in the Culinary career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Entertainer",
    code: "careers.promote entertainer",
    effect: "Promotes the active Sim in the Entertainer career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Painter",
    code: "careers.promote painter",
    effect: "Promotes the active Sim in the Painter career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Secret Agent",
    code: "careers.promote secretagent",
    effect: "Promotes the active Sim in the Secret Agent career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Tech Guru",
    code: "careers.promote techguru",
    effect: "Promotes the active Sim in the Tech Guru career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Writer",
    code: "careers.promote adult_writer",
    effect: "Promotes the active Sim in the Writer career.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Base game career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Actor",
    code: "careers.promote actor",
    effect: "Promotes the active Sim in the Actor career.",
    needsTestingCheats: true,
    dlc: "Get Famous",
    verification: "community",
    notes: "Expansion career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Detective",
    code: "careers.promote detective",
    effect: "Promotes the active Sim in the Detective career.",
    needsTestingCheats: true,
    dlc: "Get to Work",
    verification: "community",
    notes: "Expansion career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Doctor",
    code: "careers.promote doctor",
    effect: "Promotes the active Sim in the Doctor career.",
    needsTestingCheats: true,
    dlc: "Get to Work",
    verification: "community",
    notes: "Expansion career."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Careers",
    name: "Promote career: Scientist",
    code: "careers.promote adult_active_scientist",
    effect: "Promotes the active Sim in the Scientist career.",
    needsTestingCheats: true,
    dlc: "Get to Work",
    verification: "community",
    notes: "Expansion career."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Reset stuck Sim",
    code: "resetsim [FirstName] [LastName]",
    effect: "Resets a stuck Sim.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Example: resetsim Bella Goth"
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Full edit mode in Create-a-Sim",
    code: "cas.fulleditmode",
    effect: "Unlocks deeper Create-a-Sim editing options.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Use after turning on testingcheats."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Fill hunger",
    code: "fillmotive motive_Hunger",
    effect: "Fills the active Sim's hunger need.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Single need cheat."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Fill energy",
    code: "fillmotive motive_Energy",
    effect: "Fills the active Sim's energy need.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Single need cheat."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Fill all needs",
    code: "sims.fill_all_commodities",
    effect: "Fills all needs for the active household.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Useful for recovery or testing."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Give satisfaction points",
    code: "sims.give_satisfaction_points [amount]",
    effect: "Gives the active Sim satisfaction points.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Example: sims.give_satisfaction_points 5000"
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Hide plumbob and speech effects",
    code: "headlineeffects off",
    effect: "Turns off some floating effects above Sims.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Useful for screenshots."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Show plumbob and speech effects",
    code: "headlineeffects on",
    effect: "Turns floating effects back on.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Restores normal display."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Hide object hover outlines",
    code: "hovereffects off",
    effect: "Turns off hover outlines for cleaner screenshots.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Useful in build mode screenshots too."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Show object hover outlines",
    code: "hovereffects on",
    effect: "Turns hover outlines back on.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Restores normal display."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Add trait: Never Weary",
    code: "traits.equip_trait NeverWeary",
    effect: "Makes the Sim no longer need sleep.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Reward trait."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Add trait: Free Services",
    code: "traits.equip_trait FreeServices",
    effect: "Makes hired one-time services free.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Reward trait."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Add trait: Frugal",
    code: "traits.equip_trait Frugal",
    effect: "Reduces household bills.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Reward trait."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Add trait: Observant",
    code: "traits.equip_trait Observant",
    effect: "Lets Sims learn traits about others faster.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Reward trait."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Lifestyle",
    name: "Remove trait: Never Weary",
    code: "traits.remove_trait NeverWeary",
    effect: "Removes the Never Weary trait.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Restores normal sleep."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Aspirations",
    name: "Complete current aspiration milestone",
    code: "aspirations.complete_current_milestone",
    effect: "Completes the active Sim's current aspiration milestone.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Use repeatedly to keep advancing."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Build / Buy",
    name: "Move objects freely",
    code: "bb.moveobjects",
    effect: "Lets you place objects more freely in Build/Buy mode.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "One of the most useful build cheats."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Build / Buy",
    name: "Show hidden objects",
    code: "bb.showhiddenobjects",
    effect: "Reveals hidden and debug objects in Build/Buy.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Useful for collectibles and debug items."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Build / Buy",
    name: "Show live edit objects",
    code: "bb.showliveeditobjects",
    effect: "Reveals extra world and live edit objects.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Often used with bb.showhiddenobjects."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Build / Buy",
    name: "Build anywhere",
    code: "bb.enablefreebuild",
    effect: "Allows building on normally restricted lots.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Useful for hidden lots."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Build / Buy",
    name: "Ignore career unlocks",
    code: "bb.ignoregameplayunlocksentitlement",
    effect: "Unlocks Build/Buy items tied to career progression.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Good for fully unlocked builds."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Cooking",
    code: "stats.set_skill_level Major_HomestyleCooking 10",
    effect: "Sets Cooking to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Gourmet Cooking",
    code: "stats.set_skill_level Major_GourmetCooking 10",
    effect: "Sets Gourmet Cooking to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Charisma",
    code: "stats.set_skill_level Major_Charisma 10",
    effect: "Sets Charisma to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Fitness",
    code: "stats.set_skill_level Skill_Fitness 10",
    effect: "Sets Fitness to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Gardening",
    code: "stats.set_skill_level Major_Gardening 10",
    effect: "Sets Gardening to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Guitar",
    code: "stats.set_skill_level Major_Guitar 10",
    effect: "Sets Guitar to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Handiness",
    code: "stats.set_skill_level Major_Handiness 10",
    effect: "Sets Handiness to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Logic",
    code: "stats.set_skill_level Major_Logic 10",
    effect: "Sets Logic to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Painting",
    code: "stats.set_skill_level Major_Painting 10",
    effect: "Sets Painting to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Piano",
    code: "stats.set_skill_level Major_Piano 10",
    effect: "Sets Piano to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Programming",
    code: "stats.set_skill_level Major_Programming 10",
    effect: "Sets Programming to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Rocket Science",
    code: "stats.set_skill_level Major_RocketScience 10",
    effect: "Sets Rocket Science to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Video Gaming",
    code: "stats.set_skill_level Major_VideoGaming 10",
    effect: "Sets Video Gaming to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Violin",
    code: "stats.set_skill_level Major_Violin 10",
    effect: "Sets Violin to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Writing",
    code: "stats.set_skill_level Major_Writing 10",
    effect: "Sets Writing to level 10.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Replace 10 with a lower number for a partial level."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Parenting",
    code: "stats.set_skill_level skill_parenting 10",
    effect: "Sets Parenting to level 10.",
    needsTestingCheats: true,
    dlc: "Parenthood",
    verification: "community",
    notes: "Game pack skill."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Singing",
    code: "stats.set_skill_level Major_Singing 10",
    effect: "Sets Singing to level 10.",
    needsTestingCheats: true,
    dlc: "City Living",
    verification: "community",
    notes: "Expansion skill."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Skills",
    name: "Max skill: Wellness",
    code: "stats.set_skill_level major_wellness 10",
    effect: "Sets Wellness to level 10.",
    needsTestingCheats: true,
    dlc: "Spa Day",
    verification: "community",
    notes: "Game pack skill."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Relationships",
    name: "Introduce Sim to everyone",
    code: "relationship.introduce_sim_to_all_others",
    effect: "Introduces the active Sim to all other Sims.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Useful before relationship cheats."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Relationships",
    name: "Create a friend for Sim",
    code: "relationships.create_friends_for_sim",
    effect: "Creates a friend for the active Sim.",
    needsTestingCheats: false,
    dlc: "Base Game",
    verification: "community",
    notes: "Can help populate empty saves."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Relationships",
    name: "Set friendship to 100",
    code: "modifyrelationship [YourSimFirst] [YourSimLast] [TargetFirst] [TargetLast] 100 LTR_Friendship_Main",
    effect: "Raises friendship between two Sims.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Use real first and last names."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Relationships",
    name: "Set friendship to -100",
    code: "modifyrelationship [YourSimFirst] [YourSimLast] [TargetFirst] [TargetLast] -100 LTR_Friendship_Main",
    effect: "Drops friendship between two Sims.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Negative values lower the relationship."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Relationships",
    name: "Set romance to 100",
    code: "modifyrelationship [YourSimFirst] [YourSimLast] [TargetFirst] [TargetLast] 100 LTR_Romance_Main",
    effect: "Raises romance between two Sims.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Use real first and last names."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Relationships",
    name: "Set romance to -100",
    code: "modifyrelationship [YourSimFirst] [YourSimLast] [TargetFirst] [TargetLast] -100 LTR_Romance_Main",
    effect: "Drops romance between two Sims.",
    needsTestingCheats: true,
    dlc: "Base Game",
    verification: "community",
    notes: "Negative values lower the relationship."
  },

  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Occults",
    name: "Become Mermaid",
    code: "traits.equip_trait trait_OccultMermaid",
    effect: "Turns the Sim into a mermaid.",
    needsTestingCheats: true,
    dlc: "Island Living",
    verification: "community",
    notes: "Use the matching remove cheat to reverse it."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Occults",
    name: "Remove Mermaid occult",
    code: "traits.remove_trait trait_OccultMermaid",
    effect: "Turns a mermaid back into a normal Sim.",
    needsTestingCheats: true,
    dlc: "Island Living",
    verification: "community",
    notes: "Occult removal cheat."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Occults",
    name: "Become Vampire",
    code: "traits.equip_trait trait_OccultVampire",
    effect: "Turns the Sim into a vampire.",
    needsTestingCheats: true,
    dlc: "Vampires",
    verification: "community",
    notes: "Use the matching remove cheat to reverse it."
  },
  {
    game: "The Sims 4",
    platform: "PS5",
    category: "Occults",
    name: "Remove Vampire occult",
    code: "traits.remove_trait trait_OccultVampire",
    effect: "Turns a vampire back into a normal Sim.",
    needsTestingCheats: true,
    dlc: "Vampires",
    verification: "community",
    notes: "Occult removal cheat."
  }
];
